export default {
  home: '/quests',
  apiAuthSignIn: '/api/auth/signin/email',
  apiUpload: '/api/upload',
  apiCreateQuest: '/api/quests',
  apiDeleteQuest: (questId: string) => `/api/quests/${questId}`,
  apiUpdateQuest: (questId: string) => `/api/quests/${questId}`,
  apiCreateTask: (questId: string) => `/api/quests/${questId}/tasks`,
  apiUpdateTask: (taskId: string) => `/api/tasks/${taskId}`,
  apiDeleteTask: (taskId: string) => `/api/tasks/${taskId}`,
  apiMoveTask: (taskId: string) => `/api/tasks/${taskId}/move`,
  apiCreateAssignment: (questId: string) => `/api/quests/${questId}/assignments`,
  signIn: '/auth/login',
  verifyRequest: '/auth/verify-request',
  assignmentShow: (assignmentId: string) => `/assignments/${assignmentId}`,
  questNew: '/quests/new',
  questList: '/quests',
  questEdit: (questId: string) => `/quests/${questId}/edit`,
  questShow: (questId: string) => `/quests/${questId}`,
  taskShow: (taskId: string) => `/tasks/${taskId}`,
}
